### ISSUE TITLE
qmri

### ISSUE THREAD

**Issue by JohnAshburner** [balbasty/nitorch#59]
If "preproc.Register=True" and a transmit field is specified, then qmri.greeq is not happy.
opt.preproc.register = True
pd, r1, r2s, mt = qmri.greeq([pdw, t1w, mtw], transmit=b1p, receive=None, opt=opt)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jashb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nitorch\tools\qmri\relax\_mpm\_greeq.py", line 100, in greeq
    data, transmit, receive, maps = preproc(data, transmit, receive, opt)
  File "C:\Users\jashb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nitorch\tools\qmri\relax\_mpm\_preproc.py", line 131, in preproc
    data_reg += [(map.magnitude.fdata(rand=True, cache=False, **backend),
  File "C:\Users\jashb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nitorch\tools\qmri\relax\_mpm\_preproc.py", line 131, in <listcomp>
    data_reg += [(map.magnitude.fdata(rand=True, cache=False, **backend),
AttributeError: 'NoneType' object has no attribute 'fdata'

**Comment by balbasty** [comment]
Hi John,

Can you copy-paste the line that defines `b1p`? Do you provide a magnitude image (along with the estimated field) that can be used to drive registration?

**Comment by JohnAshburner** [comment]
Sorry. I didn't include a magnitude image.  My mistake.

**Comment by balbasty** [comment]
Thanks for the update! I'll add a more informative error message :-)
